### ISSUE TITLE
Preprocessing wikipedia and reproducing analogy results

### ISSUE THREAD

**Issue by belizgunel** [lateral/minkowski#3]
Hello, I was wondering what exactly you did for preprocessing the Wikipedia corpus that you pointed to in the paper. We removed punctuation (based on python’s string.punctuation list), lower-cased, and removed any word that didn't pass python.isalpha()for preprocessing. We still end up getting 502M words compared to 498M words you reported. We also can't reproduce the analogy results using the script you provided on google dataset -- it seems like they are about 40% off. If you could help us with why these might be, we would very much appreciate it!

**Comment by mleimeister** [comment]
Hi Beliz,

thanks a lot for your message and your interest in the code. 

Regarding the preprocessing, we realized that the paper does not mention that we also apply a token pattern of the form r'(?u)\b[^(\W|\d|_)]{1,}\w+\b', which filters for alpha-numeric words that don't start with a number and have at least 2 characters. Thanks for the hint that this is missing, we'll add it in an updated version. This would explain a slight difference in the cleaned training corpus.

Regarding the results, are you getting roughly the same numbers for the similarity task, but the analogy results are much worse? I reran the evaluation script and do get the numbers reported for the vectors trained with the mentioned hyperparameters. I'm not sure if a marginal difference in the corpus could explain such a high variance. To test that I could send you the cleaned training corpus as well as the vector files, so you could compare directly to your results. Let me know if this would help..

Cheers,
Matthias

**Comment by mleimeister** [comment]
Here you can find the cleaned training data, including the preprocessing script we used and the resulting embedding files: https://storage.googleapis.com/lateral-datadumps/hyperbolic_skipgram_arxiv.tar.gz

**Comment by belizgunel** [comment]
Thanks Matthias! Cleaned training data helped me get the results you reported.
